#!/usr/bin/env python3
"""hypr_theme_conf.py — Single canonical writer for ~/.config/hypr/theme.conf.

Three writers used to race on this file with competing headers/schemas:
  - dotfiles apply_wallpaper_theme.sh (full $wallpaper_* schema),
  - theme_manager.sync_hyprland (minimal general-only schema),
  - apply_custom_theme.sync_hyprland_border (minimal general-only schema).

This module owns the ONE canonical schema: the FULL variable set
($wallpaper_accent/muted/dim/inactive + general { col.active_border /
col.inactive_border }) with ONE header line. Both Python functions delegate
here; the shell script calls this module's CLI instead of maintaining its
own heredoc (shell-delegates-to-Python: smaller diff, one schema forever).

hyprland.conf keeps working via its existing `source` line; the file stays
generated and gitignored.
"""

import argparse
import colorsys
import os
import subprocess
import sys
from pathlib import Path

THEME_HEADER = (
    "# theme.conf — Generated by Cocoa theme engine "
    "(single canonical writer; do not edit, regenerated on theme change)"
)
DEFAULT_INACTIVE = "33333388"


def _clean_hex(value: str, fallback: str, allow_alpha: bool = False) -> str:
    """Normalizes a color to 6 lowercase hex digits (no leading #).

    With allow_alpha=True, an 8-digit RGBA value is accepted as-is
    (used for the inactive border, which carries its own alpha).
    """
    cleaned = (value or "").strip().lstrip("#")
    if len(cleaned) == 3 and all(c in "0123456789abcdefABCDEF" for c in cleaned):
        cleaned = "".join(c * 2 for c in cleaned)
    valid = "0123456789abcdefABCDEF"
    if len(cleaned) != 6 or any(c not in valid for c in cleaned):
        if allow_alpha and len(cleaned) == 8 and all(c in valid for c in cleaned):
            return cleaned.lower()
        cleaned = fallback.lstrip("#")
    return cleaned.lower()


def _clamp(val: float, lo: float, hi: float) -> float:
    return max(lo, min(hi, val))


def derive_muted_dim(accent_hex: str) -> tuple:
    """Derives muted/dim companions from an accent color (HLS transform).

    Mirrors the ratios used by apply_custom_theme.derive_palette_from_accent
    so single-accent callers get consistent companions without importing it
    (avoids a theme_manager <-> apply_custom_theme import cycle).
    """
    cleaned = _clean_hex(accent_hex, "88c0d0")
    r = int(cleaned[0:2], 16) / 255.0
    g = int(cleaned[2:4], 16) / 255.0
    b = int(cleaned[4:6], 16) / 255.0
    h, lightness, saturation = colorsys.rgb_to_hls(r, g, b)

    s_muted = _clamp(saturation * 0.65, 0.15, 0.45)
    l_muted = _clamp(lightness * 0.85, 0.50, 0.72)
    rm, gm, bm = colorsys.hls_to_rgb(h, l_muted, s_muted)

    s_dim = _clamp(saturation * 0.30, 0.08, 0.25)
    l_dim = _clamp(lightness * 0.60, 0.30, 0.50)
    rd, gd, bd = colorsys.hls_to_rgb(h, l_dim, s_dim)

    muted = f"{int(rm * 255):02x}{int(gm * 255):02x}{int(bm * 255):02x}"
    dim = f"{int(rd * 255):02x}{int(gd * 255):02x}{int(bd * 255):02x}"
    return muted, dim


def render_theme_conf(
    accent_hex: str,
    muted_hex: str = None,
    dim_hex: str = None,
    inactive: str = DEFAULT_INACTIVE,
) -> str:
    """Renders the canonical theme.conf content (pure, test-friendly)."""
    accent = _clean_hex(accent_hex, "88c0d0")
    if muted_hex is None or dim_hex is None:
        derived_muted, derived_dim = derive_muted_dim(accent)
        muted = _clean_hex(muted_hex, derived_muted) if muted_hex else derived_muted
        dim = _clean_hex(dim_hex, derived_dim) if dim_hex else derived_dim
    else:
        muted = _clean_hex(muted_hex, accent)
        dim = _clean_hex(dim_hex, accent)
    inactive_clean = _clean_hex(inactive, DEFAULT_INACTIVE, allow_alpha=True)
    lines = [
        THEME_HEADER,
        "",
        f"$wallpaper_accent = rgb({accent})",
        f"$wallpaper_accent_alpha = rgba({accent}ff)",
        f"$wallpaper_muted = rgb({muted})",
        f"$wallpaper_dim = rgb({dim})",
        f"$wallpaper_inactive = rgba({inactive_clean})",
        "",
        "general {",
        "    col.active_border = $wallpaper_accent",
        "    col.inactive_border = $wallpaper_inactive",
        "}",
        "",
    ]
    return "\n".join(lines)


def default_theme_conf_path() -> Path:
    """Returns ~/.config/hypr/theme.conf for the current user."""
    return Path.home() / ".config/hypr/theme.conf"


def write_theme_conf(
    accent_hex: str,
    muted_hex: str = None,
    dim_hex: str = None,
    path=None,
) -> str:
    """Atomically writes the canonical theme.conf; returns the path used."""
    dest = Path(path) if path else default_theme_conf_path()
    dest.parent.mkdir(parents=True, exist_ok=True)
    tmp = dest.with_suffix(".tmp")
    with open(tmp, "w", encoding="utf-8") as f:
        f.write(render_theme_conf(accent_hex, muted_hex, dim_hex))
    os.replace(tmp, dest)
    return str(dest)


def sync_live_border(accent_hex: str) -> None:
    """Applies border colors to the running compositor via hyprctl (fail-soft)."""
    accent = _clean_hex(accent_hex, "88c0d0")
    if not (os.environ.get("HYPRLAND_INSTANCE_SIGNATURE") or Path("/tmp/hypr").exists()):
        return
    try:
        subprocess.run(
            ["hyprctl", "keyword", "general:col.active_border", f"rgb({accent})"],
            capture_output=True,
            timeout=2,
        )
        subprocess.run(
            ["hyprctl", "keyword", "general:col.inactive_border", f"rgba({DEFAULT_INACTIVE})"],
            capture_output=True,
            timeout=2,
        )
    except Exception:
        pass


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description="Canonical writer for Hyprland theme.conf")
    parser.add_argument("accent", help="Accent color hex (e.g. d1e7ae)")
    parser.add_argument("muted", nargs="?", default=None, help="Muted companion hex")
    parser.add_argument("dim", nargs="?", default=None, help="Dim companion hex")
    parser.add_argument("--path", default=None, help="Output path (default: ~/.config/hypr/theme.conf)")
    parser.add_argument("--no-live", action="store_true", help="Skip live hyprctl sync")
    args = parser.parse_args(argv)

    dest = write_theme_conf(args.accent, args.muted, args.dim, args.path)
    if not args.no_live:
        sync_live_border(args.accent)
    print(dest)
    return 0


if __name__ == "__main__":
    sys.exit(main())
